const scanData2009NE = {
    "url": "https://www.nonnativespecies.org/non-native-species/risk-analysis/horizonscanning",
    "Alopex lagopus": {"common_name": "Arctic fox", "list_category": "Alert list", "environmental_risk": "High"},
    "Castor canadensis": {"common_name": "American beaver", "list_category": "Alert list", "environmental_risk": "High"},
    "Felis bengalensis": {"common_name": "leopard cat", "list_category": "Alert list", "environmental_risk": "High"},
    "Hydrochoerus hydrochaeris": {"common_name": "capybara", "list_category": "Alert list", "environmental_risk": "High"},
    "Myocastor coypus": {"common_name": "coypu", "list_category": "Alert list", "environmental_risk": "High"},
    "Nyctereutes procyonoides": {"common_name": "raccoon dog", "list_category": "Alert list", "environmental_risk": "High"},
    "Ondatra zibethicus": {"common_name": "muskrat", "list_category": "Alert list", "environmental_risk": "High"},
    "Procyon lotor": {"common_name": "raccoon", "list_category": "Alert list", "environmental_risk": "High"},
    "Glis glis": {"common_name": "edible dormouse", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Hydropotes inermis": {"common_name": "chinese water deer", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Aonyx cinerea": {"common_name": "short-clawed otter", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Cynomys ludovicianus": {"common_name": "black-tailed prairie dog", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Mephitis mephitis": {"common_name": "striped skunk", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Nasua nasua": {"common_name": "coatimundi", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Tamias sibiricus": {"common_name": "Siberian chipmunk", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Tamias striatus": {"common_name": "Eastern chipmunk", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Callithrix spp": {"common_name": "marmoset", "list_category": "None", "environmental_risk": "Low"},
    "Cebus spp": {"common_name": "capuchin", "list_category": "None", "environmental_risk": "Low"},
    "Chinchilla spp": {"common_name": "chinchilla", "list_category": "None", "environmental_risk": "Low"},
    "Eliomys quercinus": {"common_name": "garden dormouse", "list_category": "None", "environmental_risk": "Low"},
    "Hystrix brachyura": {"common_name": "Himalayan porcupine", "list_category": "None", "environmental_risk": "Low"},
    "Hystrix cristata": {"common_name": "crested porcupine", "list_category": "None", "environmental_risk": "Low"},
    "Mesocricetus auratus": {"common_name": "golden hamster", "list_category": "None", "environmental_risk": "Low"},
    "Petaurus breviceps": {"common_name": "sugar glider", "list_category": "None", "environmental_risk": "Low"},
    "Atelerix albiventris": {"common_name": "African pygmy hedgehog", "list_category": "Climate list", "environmental_risk": "Medium"},
    "Alopochen aegyptiacus": {"common_name": "Egyptian goose", "list_category": "Black list", "environmental_risk": "High"},
    "Bubo bubo": {"common_name": "eagle owl", "list_category": "Black list", "environmental_risk": "High"},
    "Acridotheres tristis": {"common_name": "common mynah", "list_category": "Alert list", "environmental_risk": "High"},
    "Threskionis aethiopicus": {"common_name": "sacred ibis", "list_category": "Alert list", "environmental_risk": "High"},
    "Corvus splendens": {"common_name": "Indian House Crow", "list_category": "Alert list", "environmental_risk": "High"},
    "Branta leucopsis": {"common_name": "barnacle goose", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Anser caerulescens": {"common_name": "snow goose", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Anser indicus": {"common_name": "bar-headed goose", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Bubulcus ibis": {"common_name": "cattle egret", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Cairina moschata": {"common_name": "Muscovy duck", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Cygnus atratus": {"common_name": "black swan", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Netta rufina": {"common_name": "red-crested pochard", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Tadorna ferruginea": {"common_name": "ruddy shelduck", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Acridotheres cristatellus": {"common_name": "crested mynah", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Acridotheres ginginianus": {"common_name": "bank mynah", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Chloephaga picta": {"common_name": "upland goose", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Nycticorax nycticorax": {"common_name": "night heron", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Molothrus spp": {"common_name": "cowbirds", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Aix galericulata": {"common_name": "Mandarin duck", "list_category": "None", "environmental_risk": "Low"},
    "Myiopsitta monachus": {"common_name": "monk parakeet", "list_category": "None", "environmental_risk": "Low"},
    "Aratinga acuticaudata": {"common_name": "blue-crowned parakeet", "list_category": "None", "environmental_risk": "Low"},
    "Branta sandvicensis": {"common_name": "Hawaiian goose", "list_category": "None", "environmental_risk": "Low"},
    "Psittacula eupatria": {"common_name": "Alexandrine parakeet", "list_category": "None", "environmental_risk": "Low"},
    "Pycnonotus cafer": {"common_name": "red-vented bulbul", "list_category": "None", "environmental_risk": "Low"},
    "Passer hispaniolensis": {"common_name": "Spanish sparrow", "list_category": "None", "environmental_risk": "Low"},
    "Pelophylax ridibundus": {"common_name": "marsh frog", "list_category": "Black list", "environmental_risk": "High"},
    "Rana catesbeiana": {"common_name": "North American bullfrog", "list_category": "Black list", "environmental_risk": "High"},
    "Xenopus laevis": {"common_name": "African clawed toad", "list_category": "Black list", "environmental_risk": "High"},
    "Alytes obstetricans": {"common_name": "midwife toad", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Rana esculenta": {"common_name": "edible frog", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Triturus carniflex": {"common_name": "Italian crested newt", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Triturus alpestris": {"common_name": "Alpine newt", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Bombina spp": {"common_name": "fire-bellied toads", "list_category": "None", "environmental_risk": "Low"},
    "Hyla arborea": {"common_name": "European tree frog", "list_category": "None", "environmental_risk": "Low"},
    "Bufo marinus": {"common_name": "cane toad", "list_category": "Climate list", "environmental_risk": "High"},
    "Eleutherodactylus coqui": {"common_name": "Carribean tree-frog", "list_category": "Climate list", "environmental_risk": "Medium"},
    "Osteopilus septentrionalis": {"common_name": "Cuban tree frog", "list_category": "Climate list", "environmental_risk": "Medium"},
    "Chelydra serpentina": {"common_name": "snapping turtle", "list_category": "Black list", "environmental_risk": "High"},
    "Trachemys scripta": {"common_name": "red-eared terrapin (slider)", "list_category": "Black list", "environmental_risk": "High"},
    "Chrysemys picta": {"common_name": "painted turtle", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Emys orbicularis": {"common_name": "European pond terrapin", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Mauremys caspica": {"common_name": "stripe-necked terrapin", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Elaphe spp": {"common_name": "rat snakes", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Lampropeltis spp": {"common_name": "king/milk snakes", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Thamnophis spp": {"common_name": "garter snakes", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Elaphe longissima": {"common_name": "Aesculapian snake", "list_category": "None", "environmental_risk": "Low"},
    "Lacerta viridis": {"common_name": "green lizard", "list_category": "None", "environmental_risk": "Low"},
    "Podarcis muralis": {"common_name": "wall lizard", "list_category": "None", "environmental_risk": "Low"},
    "Boa constrictor imperator": {"common_name": "common boa", "list_category": "Climate list", "environmental_risk": "High"},
    "Python molurus bivittatus": {"common_name": "Burmese python", "list_category": "Climate list", "environmental_risk": "High"},
    "Agamidae": {"common_name": "dragons", "list_category": "Climate list", "environmental_risk": "Low"},
    "Chamaeleonidae": {"common_name": "chamaeleons", "list_category": "Climate list", "environmental_risk": "Low"},
    "Gekkonidae": {"common_name": "geckos", "list_category": "Climate list", "environmental_risk": "Low"},
    "Iguanidae": {"common_name": "iguanas", "list_category": "Climate list", "environmental_risk": "Low"},
    "Lymantria dispar": {"common_name": "gypsy moth", "list_category": "Black list", "environmental_risk": "High"},
    "Agrilus planipennis": {"common_name": "emerald ash borer", "list_category": "Alert list", "environmental_risk": "High"},
    "Anoplophora chinensis": {"common_name": "citrus longhorn beetle", "list_category": "Alert list", "environmental_risk": "High"},
    "Anoplophora glabripennis": {"common_name": "Asian longhorn beetle", "list_category": "Alert list", "environmental_risk": "High"},
    "Bursaphelenchus xylophilus": {"common_name": "pinewood nematode", "list_category": "Alert list", "environmental_risk": "High"},
    "Thaumetopoea processionea": {"common_name": "oak processionary moth", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Dryocosmus kuriphilus": {"common_name": "oriental chestnut gall wasp", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Ips typographus": {"common_name": "eight-toothed bark beetle", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Lissorhoptrus oryzophilus": {"common_name": "American water weevil", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Monochamus sartor": {"common_name": "sawyer beetle", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Popillia japonica": {"common_name": "Japanese beetle", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Selonochlamys ysbryda": {"common_name": "ghost slug", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Leptoglossus occidentalis": {"common_name": "western conifer seedbug", "list_category": "None", "environmental_risk": "Low"},
    "Diaphania perspectalis": {"common_name": "a pyralid moth", "list_category": "None", "environmental_risk": "Low"},
    "Dasineura oxycoccana": {"common_name": "blueberry gall midge", "list_category": "None", "environmental_risk": "Low"},
    "Nysius huttoni": {"common_name": "green chinch bug", "list_category": "None", "environmental_risk": "Low"},
    "Tinocallis takachihoensis": {"common_name": "aphid feeding on Ulmus sp.", "list_category": "None", "environmental_risk": "Low"},
    "Callidiellum rufipenne": {"common_name": "cedar longhorned beetle", "list_category": "None", "environmental_risk": "Low"},
    "Ceresa alta": {"common_name": "buffalo treehopper", "list_category": "None", "environmental_risk": "Low"},
    "Corythucha arcuata": {"common_name": "oak lace bug", "list_category": "None", "environmental_risk": "Low"},
    "Diaspidiotus perniciosus": {"common_name": "San Jose scale", "list_category": "None", "environmental_risk": "Low"},
    "Enaphalodes rufulus": {"common_name": "red oak borer", "list_category": "None", "environmental_risk": "Low"},
    "Liriomyza chinensis": {"common_name": "onion leafminer", "list_category": "None", "environmental_risk": "Low"},
    "Listrodes difficilis": {"common_name": "vegetable weevil", "list_category": "None", "environmental_risk": "Low"},
    "Matsucoccus feytaudi": {"common_name": "maritime pine scale", "list_category": "None", "environmental_risk": "Low"},
    "Megastigmus nigrovariegatus": {"common_name": "American rose seed chalcid", "list_category": "None", "environmental_risk": "Low"},
    "Metcalfa pruinosa": {"common_name": "frosted moth-bug", "list_category": "None", "environmental_risk": "Low"},
    "Mogulones geographicus": {"common_name": "a weevil", "list_category": "None", "environmental_risk": "Low"},
    "Monochamus alternatus": {"common_name": "Japanese pine sawyer", "list_category": "None", "environmental_risk": "Low"},
    "Monochamus sutor": {"common_name": "small white-marmorated longicorn", "list_category": "None", "environmental_risk": "Low"},
    "Monema flavescens": {"common_name": "oriental moth", "list_category": "None", "environmental_risk": "Low"},
    "Naupactus leucoloma": {"common_name": "white-fringed weevil", "list_category": "None", "environmental_risk": "Low"},
    "Pseudaulacaspis pentagona": {"common_name": "white peach scale", "list_category": "None", "environmental_risk": "Low"},
    "Sitona discoideus": {"common_name": "a weevil", "list_category": "None", "environmental_risk": "Low"},
    "Stephanitis oberti": {"common_name": "blackberry lacebug", "list_category": "None", "environmental_risk": "Low"},
    "Linepithema humile": {"common_name": "Argentine Ant", "list_category": "Climate list", "environmental_risk": "High"},
    "Neogobius melanostomus": {"common_name": "Round goby", "list_category": "Alert list", "environmental_risk": "High"},
    "Proterorhinus marmoratus": {"common_name": "Tubenose goby", "list_category": "Alert list", "environmental_risk": "High"},
    "Ameiurus melas/Ictalurus punctatus": {"common_name": "Ictalurid catfishes", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Gambusia holbrooki": {"common_name": "Eastern mosquitofish", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Acipenser ruthenus": {"common_name": "Sterlet", "list_category": "None", "environmental_risk": "Low"},
    "Aristichthys nobilis": {"common_name": "Bighead carp", "list_category": "None", "environmental_risk": "Low"},
    "Catostomus commersoni": {"common_name": "White sucker", "list_category": "None", "environmental_risk": "Low"},
    "Ctenopharyngodon idella": {"common_name": "Grass carp", "list_category": "None", "environmental_risk": "Low"},
    "Hypophthalmichthys molitrix": {"common_name": "Silver carp", "list_category": "None", "environmental_risk": "Low"},
    "Misgurnus fossilis/anguillicaudatus": {"common_name": "Weatherfishes", "list_category": "None", "environmental_risk": "Low"},
    "Pimephales promelas": {"common_name": "Fathead minnow", "list_category": "None", "environmental_risk": "Low"},
    "Cyprinella lutrensis": {"common_name": "Red shiner", "list_category": "None", "environmental_risk": "Low"},
    "Eriocheir sinensis": {"common_name": "Chinese Mitten Crab", "list_category": "Black list", "environmental_risk": "High"},
    "Mytilopsis leucophaeata": {"common_name": "False Dark Muscle", "list_category": "Black list", "environmental_risk": "High"},
    "Orchonectes limosus": {"common_name": "Spiny Cheeked Crayfish", "list_category": "Black list", "environmental_risk": "High"},
    "Procambarus sp.": {"common_name": "Marbled Crayfish", "list_category": "Alert list", "environmental_risk": "High"},
    "Astacus leptodactylus": {"common_name": "Turkish Narrow-Clawed Crayfish", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Corbicula fluminea": {"common_name": "Asian Clam", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Procambarus clarkii": {"common_name": "Red Swamp Crayfish", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Achtheres percarum": {"common_name": "Parasitic Copepod", "list_category": "None", "environmental_risk": "Low"},
    "Branchiura sowerbyi": {"common_name": "Oligochaete Worm", "list_category": "None", "environmental_risk": "Low"},
    "Corophium curvispinum": {"common_name": "Freshwater Malacostracan", "list_category": "None", "environmental_risk": "Low"},
    "Craspedacusta sowerbyi": {"common_name": "Amazonian Jellyfish", "list_category": "None", "environmental_risk": "Low"},
    "Ergasilus sieboldi": {"common_name": "Parasitic Copepod", "list_category": "None", "environmental_risk": "Low"},
    "Ergasilus briani": {"common_name": "Parasitic Copepod", "list_category": "None", "environmental_risk": "Low"},
    "Ferissia wautieri": {"common_name": "Wautier's Limpet", "list_category": "None", "environmental_risk": "Low"},
    "Masculinium traversum": {"common_name": "Long fingernail clam / Oblong orb mussel", "list_category": "None", "environmental_risk": "Low"},
    "Marstoniopsis scholtzi": {"common_name": "Taylor's Spire Shell", "list_category": "None", "environmental_risk": "Low"},
    "Menetus dilatatus": {"common_name": "Trumpet Ramshorn", "list_category": "None", "environmental_risk": "Low"},
    "Neoergasilus japonicus": {"common_name": "Parasitic Copepod", "list_category": "None", "environmental_risk": "Low"},
    "Physella acuta": {"common_name": "Tadpole snail", "list_category": "None", "environmental_risk": "Low"},
    "Physella gyrina": {"common_name": "Pouch snail", "list_category": "None", "environmental_risk": "Low"},
    "Physella heterostopha": {"common_name": "Pond snail", "list_category": "None", "environmental_risk": "Low"},
    "Tracheliastes polycolpus": {"common_name": "Parasitic Copepod", "list_category": "None", "environmental_risk": "Low"},
    "Astacus astacus": {"common_name": "Noble Crayfish", "list_category": "None", "environmental_risk": "Low"},
    "Asellus communis": {"common_name": "Freshwater Malacostracan", "list_category": "None", "environmental_risk": "Low"},
    "Dugesia tigrina": {"common_name": "Freshwater triclad", "list_category": "None", "environmental_risk": "Low"},
    "Planaria torva": {"common_name": "Freshwater triclad", "list_category": "None", "environmental_risk": "Low"},
    "Limnodrilus cervix": {"common_name": "Oligochaete Worm", "list_category": "None", "environmental_risk": "Low"},
    "Phagocata woodworthi": {"common_name": "American freshwater flatworm", "list_category": "None", "environmental_risk": "Low"},
    "Didemnum vexillum": {"common_name": "Colonial ascidian", "list_category": "Black list", "environmental_risk": "High"},
    "Paralithodes camtschaticus": {"common_name": "Red king crab", "list_category": "Alert list", "environmental_risk": "High"},
    "Watersipora subtorquata": {"common_name": "Bryozoan", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Marsupenaeus japonicus": {"common_name": "Japanese tiger prawn", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Rapana venosa": {"common_name": "Veined (Asian) rapa whelk", "list_category": "Watch list", "environmental_risk": "Medium"},
    "Ammothea hilgendorfi": {"common_name": "Sea spider", "list_category": "None", "environmental_risk": "Low"}
}