const scanDataPlantlife2010 = {
  "url": "https://www.nonnativespecies.org/non-native-species/risk-analysis/horizonscanning",
  "Abies grandis": {"common_name": "Giant fir", "priority": "Low risk"},
  "Abies procera": {"common_name": "Noble fir", "priority": "Low risk"},
  "Acaena novae-zelandiae": {"common_name": "Pirri-pirri-bur", "priority": "Critical"},
  "Acer cappadocicum": {"common_name": "Cappadocian maple", "priority": "Low risk"},
  "Acer saccharinum": {"common_name": "Silver maple", "priority": "Low risk"},
  "Acorus calamus": {"common_name": "Sweet flag", "priority": "Urgent"},
  "Acorus gramineus": {"common_name": "Slender sweet flag", "priority": "Low risk"},
  "Acorus gramineus 'Pusillus'": {"common_name": "Miniature sweet flag", "priority": "Moderate risk"},
  "Aesculus carnea": {"common_name": "Red horse chestnut", "priority": "Low risk"},
  "Aesculus indica": {"common_name": "Indian horse chestnut", "priority": "Low risk"},
  "Ailanthus altissima": {"common_name": "Tree-of-heaven", "priority": "Critical"},
  "Alchemilla mollis": {"common_name": "Garden lady's-mantle", "priority": "Moderate risk"},
  "Alisma parviflora": {"common_name": "American water-plantain", "priority": "Moderate risk"},
  "Allium subhirsutum": {"common_name": "Hairy garlic", "priority": "Low risk"},
  "Allium triquetrum": {"common_name": "Three-cornered garlic", "priority": "Critical"},
  "Alnus cordata": {"common_name": "Italian alder", "priority": "Urgent"},
  "Alocasia x amazonica": {"common_name": "Amazon lily", "priority": "Low risk"},
  "Alocasia cucullata": {"common_name": "Chinese taro", "priority": "Moderate risk"},
  "Alocasia odora": {"common_name": "Upright elephants ears", "priority": "Low risk"},
  "Alocasia plumbea": {"common_name": "Elephant ear", "priority": "Low risk"},
  "Alpinia zerumbet 'Variegata'": {"common_name": "Pink porcelain lily", "priority": "Low risk"},
  "Alstroemeria aurea": {"common_name": "Peruvian lily", "priority": "Urgent"},
  "Alternanthera reineckii": {"common_name": "", "priority": "Low risk"},
  "Alternanthera sessilis": {"common_name": "Sessile joyweed", "priority": "Low risk"},
  "Alternanthera 'Sunset'": {"common_name": "", "priority": "Low risk"},
  "Alternanthera tenella": {"common_name": "", "priority": "Low risk"},
  "Alyssum saxatile": {"common_name": "Golden Alison", "priority": "Low risk"},
  "Amaranthus bouchonii": {"common_name": "Indehiscent amaranth", "priority": "Low risk"},
  "Amaranthus hybridus": {"common_name": "Green amaranth", "priority": "Low risk"},
  "Ambrosia artemisiifolia": {"common_name": "Ragweed", "priority": "Low risk"},
  "Ambulia aromatica": {"common_name": "", "priority": "Low risk"},
  "Ammania gracilis": {"common_name": "Large ammania", "priority": "Low risk"},
  "Ammania senegalensis": {"common_name": "", "priority": "Low risk"},
  "Ampelodesmos pliniana": {"common_name": "", "priority": "Urgent"},
  "Amsonia hubrichtii": {"common_name": "Hubrischt's bluestar", "priority": "Low risk"},
  "Amsonia orientalis": {"common_name": "Eastern bluestar", "priority": "Low risk"},
  "Amsonia tabernaemontana": {"common_name": "Eastern bluestar", "priority": "Low risk"},
  "Anemone blanda": {"common_name": "Balkan anemone", "priority": "Low risk"},
  "Anemopsis californica": {"common_name": "Yerba mansa", "priority": "Low risk"},
  "Anthemis punctata": {"common_name": "Sicilian chamomile", "priority": "Low risk"},
  "Anubias afzelii": {"common_name": "", "priority": "Low risk"},
  "Anubias angustifolia": {"common_name": "", "priority": "Low risk"},
  "Anubias barteri": {"common_name": "", "priority": "Low risk"},
  "Anubias caladiifolia": {"common_name": "", "priority": "Low risk"},
  "Anubias callos": {"common_name": "", "priority": "Low risk"},
  "Anubias coffeefolia": {"common_name": "", "priority": "Low risk"},
  "Anubias congensis": {"common_name": "", "priority": "Low risk"},
  "Anubias gigantea": {"common_name": "", "priority": "Low risk"},
  "Anubias gracilis": {"common_name": "", "priority": "Low risk"},
  "Anubias hastifolia": {"common_name": "", "priority": "Low risk"},
  "Anubias heterophylla": {"common_name": "", "priority": "Low risk"},
  "Anubias lanceolata": {"common_name": "", "priority": "Low risk"},
  "Anubias nana": {"common_name": "Dwarf anubias", "priority": "Low risk"},
  "Aponogeton capuronii": {"common_name": "Corkscrew lace plant", "priority": "Low risk"},
  "Aponogeton crispus": {"common_name": "", "priority": "Low risk"},
  "Aponogeton distachyos": {"common_name": "Cape-pondweed", "priority": "Moderate risk"},
  "Aponogeton elongatus": {"common_name": "", "priority": "Low risk"},
  "Aponogeton fenestralis": {"common_name": "", "priority": "Low risk"},
  "Aponogeton henkelianus": {"common_name": "Narrow-leaved lace plant", "priority": "Low risk"},
  "Aponogeton krauseanus": {"common_name": "", "priority": "Low risk"},
  "Aponogeton longiplumulosus": {"common_name": "", "priority": "Low risk"},
  "Aponogeton madagascarensis": {"common_name": "", "priority": "Low risk"},
  "Aponogeton natans": {"common_name": "", "priority": "Low risk"},
  "Aponogeton rigidifolius": {"common_name": "", "priority": "Low risk"},
  "Aponogeton siamensis": {"common_name": "", "priority": "Low risk"},
  "Aponogeton ulvaceus": {"common_name": "", "priority": "Low risk"},
  "Aponogeton undulatus": {"common_name": "", "priority": "Low risk"},
  "Araucaria araucana": {"common_name": "Monkey-puzzle", "priority": "Low risk"},
  "Aruncus dioicus": {"common_name": "Buck's-beard", "priority": "Low risk"},
  "Arundo donax": {"common_name": "Giant reed", "priority": "Urgent"},
  "Aucuba japonica": {"common_name": "Spotted-laurel", "priority": "Low risk"},
  "Azolla caroliniana": {"common_name": "Carolina mosquito fern", "priority": "Critical"},
  "Azolla filiculoides": {"common_name": "Water fern", "priority": "Critical"},
  "Bacopa caroliniana": {"common_name": "Giant babies tears", "priority": "Moderate risk"},
  "Bacopa lanigera": {"common_name": "", "priority": "Low risk"},
  "Bacopa monnieri": {"common_name": "Coastal water hyacinth", "priority": "Low risk"},
  "Bacopa myriophylloides": {"common_name": "Fine-leaved water-hyssop", "priority": "Low risk"},
  "Bacopa rotundifolia": {"common_name": "Disk water-hyssop", "priority": "Moderate risk"},
  "Barclaya longifolia": {"common_name": "Orchid lily", "priority": "Low risk"},
  "Bassia scoparia": {"common_name": "Summer-cypress", "priority": "Low risk"},
  "Baumea rubiginosa": {"common_name": "Soft twig", "priority": "Low risk"},
  "Berberis darwinii x empetrifolia": {"common_name": "Darwin's barberry", "priority": "Low risk"},
  "Berberis gagnepainii": {"common_name": "Gagnepain's barberry", "priority": "Low risk"},
  "Berberis julianae": {"common_name": "Chinese barberry", "priority": "Low risk"},
  "Berberis thunbergii": {"common_name": "Thunberg's barberry", "priority": "Moderate risk"},
  "Bergenia crassifolia": {"common_name": "Elephant-ears", "priority": "Low risk"},
  "Beta vulgaris subsp. cicla": {"common_name": "Root beet", "priority": "Low risk"},
  "Bidens connata": {"common_name": "London bur-marigold", "priority": "Low risk"},
  "Blyxa aubertii": {"common_name": "Bamboo plant", "priority": "Moderate risk"},
  "Blyxa japonica": {"common_name": "", "priority": "Low risk"},
  "Bolbitis heteroclita": {"common_name": "El nino fern", "priority": "Low risk"},
  "Bolbitis heudelotii": {"common_name": "", "priority": "Low risk"},
  "Brachyglottis monroi": {"common_name": "Monro's ragwort", "priority": "Low risk"},
  "Brachyglottis 'Sunshine'": {"common_name": "Hedge ragwort", "priority": "Low risk"},
  "Brunnera macrophylla": {"common_name": "Great forget-me-not", "priority": "Low risk"},
  "Buddleja davidii": {"common_name": "Butterfly-bush", "priority": "Critical"},
  "Buddleja davidii x globosa (B. x weyeriana)": {"common_name": "Butterfly-bush", "priority": "Low risk"},
  "Buddleja globosa": {"common_name": "Orange-ball-tree", "priority": "Urgent"},
  "Cabomba aquatica": {"common_name": "Fanwort", "priority": "Low risk"},
  "Cabomba caroliniana": {"common_name": "Carolina water-shield", "priority": "Critical"},
  "Cabomba furcata": {"common_name": "Red Cabomba", "priority": "Low risk"},
  "Calla palustris": {"common_name": "Bog arum", "priority": "Moderate risk"},
  "Caltha introloba": {"common_name": "Alpine marsh-marigold", "priority": "Low risk"},
  "Caltha leptosepala": {"common_name": "White marsh-marigold", "priority": "Moderate risk"},
  "Caltha natans": {"common_name": "Floating marsh-marigold", "priority": "Low risk"},
  "Caltha palustris subsp. polypetala": {"common_name": "Giant kingcup", "priority": "Moderate risk"},
  "Caltha palustris var. barthei": {"common_name": "", "priority": "Moderate risk"},
  "Caltha palustris var. radicans": {"common_name": "", "priority": "Moderate risk"},
  "Caltha sagittata": {"common_name": "", "priority": "Low risk"},
  "Campanula portenschlagiana": {"common_name": "Adria bellflower", "priority": "Low risk"},
  "Campanula poscharskyana": {"common_name": "Trailing bellflower", "priority": "Moderate risk"},
  "Canna tuerckheimii": {"common_name": "", "priority": "Low risk"},
  "Cardamine corymbosa": {"common_name": "New Zealand bitter-cress", "priority": "Urgent"},
  "Cardamine lyrata": {"common_name": "Chinese ivy", "priority": "Moderate risk"},
  "Cardamine macrophylla": {"common_name": "Large-leaved cuckooflower", "priority": "Moderate risk"},
  "Cardamine raphanifolia": {"common_name": "Greater cuckooflower", "priority": "Critical"},
  "Carex muskingumensis": {"common_name": "Musk sedge", "priority": "Moderate risk"},
  "Ceratochloa carinata": {"common_name": "California brome", "priority": "Urgent"},
  "Ceratopteris cornuta": {"common_name": "", "priority": "Low risk"},
  "Ceratopteris thalictroides": {"common_name": "Sumatra fern", "priority": "Low risk"},
  "Chamaecyparis lawsoniana": {"common_name": "Lawson's cypress", "priority": "Critical"},
  "Chamaecyparis nootkatensis": {"common_name": "Nootka cypress", "priority": "Low risk"},
  "Chionodoxa forbesii": {"common_name": "Glory-of-the-snow", "priority": "Low risk"},
  "Chionodoxa sardensis": {"common_name": "Lesser glory-of-the-snow", "priority": "Low risk"},
  "Chladophora aegagrophila": {"common_name": "Marimbo", "priority": "Low risk"},
  "Chlorophytum bechettii": {"common_name": "", "priority": "Low risk"},
  "Chlorophytum 'Pongol Sword'": {"common_name": "", "priority": "Low risk"},
  "Conyza sumatrensis": {"common_name": "Guernsey fleabane", "priority": "Low risk"},
  "Cordyline australis": {"common_name": "Cabbage-palm", "priority": "Low risk"},
  "Cornus alba": {"common_name": "White dogwood", "priority": "Urgent"},
  "Cornus mas": {"common_name": "Cornelian-cherry", "priority": "Low risk"},
  "Cortaderia richardii": {"common_name": "Early pampas-grass", "priority": "Critical"},
  "Cortaderia selloana": {"common_name": "Pampas-grass", "priority": "Urgent"},
  "Corydalis cheilanthifolia": {"common_name": "Fern-leaved corydalis", "priority": "Low risk"},
  "Cotoneaster atropurpureus": {"common_name": "Purple-flowered cotoneaster", "priority": "Low risk"},
  "Cotoneaster bullatus": {"common_name": "Hollyberry cotoneaster", "priority": "Critical"},
  "Cotoneaster conspicuus": {"common_name": "Tibetan cotoneaster", "priority": "Urgent"},
  "Cotoneaster conspicuus x dammeri C. x suecicus": {"common_name": "Tibetan cotoneaster", "priority": "Critical"},
  "Cotoneaster dammeri": {"common_name": "Bearberry cotoneaster", "priority": "Critical"},
  "Cotoneaster dielsianus": {"common_name": "Diels' cotoneaster", "priority": "Critical"},
  "Cotoneaster divaricatus": {"common_name": "Spreading cotoneaster", "priority": "Urgent"},
  "Cotoneaster franchetii": {"common_name": "Franchet's cotoneaster", "priority": "Urgent"},
  "Cotoneaster frigidus x salicifolius": {"common_name": "Tree cotoneaster", "priority": "Critical"},
  "Cotoneaster hjelmqvistii": {"common_name": "Hjelmqvist's cotoneaster", "priority": "Critical"},
  "Cotoneaster horizontalis": {"common_name": "Wall cotoneaster", "priority": "Critical"},
  "Cotoneaster lacteus": {"common_name": "Late cotoneaster", "priority": "Critical"},
  "Cotoneaster microphyllus agg.": {"common_name": "Small-leaved cotoneasters", "priority": "Critical"},
  "Cotoneaster obtusus": {"common_name": "Dartford cotoneaster", "priority": "Low risk"},
  "Cotoneaster prostratus": {"common_name": "Procumbent cotoneaster", "priority": "Critical"},
  "Cotoneaster rehderi": {"common_name": "Bullate cotoneaster", "priority": "Critical"},
  "Cotoneaster salicifolius": {"common_name": "Willow-leaved cotoneaster", "priority": "Critical"},
  "Cotoneaster simonsii": {"common_name": "Himalayan cotoneaster", "priority": "Critical"},
  "Cotoneaster sternianus": {"common_name": "Stern's cotoneaster", "priority": "Critical"},
  "Cotula coronopifolia": {"common_name": "Buttonweed", "priority": "Urgent"},
  "Crassula helmsii": {"common_name": "New Zealand pigmyweed", "priority": "Critical"},
  "Crinum calamistratum": {"common_name": "", "priority": "Low risk"},
  "Crinum erubescens": {"common_name": "Swamp lily", "priority": "Low risk"},
  "Crinum natans": {"common_name": "", "priority": "Low risk"},
  "Crinum thaianum": {"common_name": "", "priority": "Low risk"},
  "Crocosmia paniculata": {"common_name": "Aunt-Eliza", "priority": "Critical"},
  "Crocosmia pottsii": {"common_name": "Pott's montbretia", "priority": "Critical"},
  "Crocosmia x crocosmiiflora": {"common_name": "Montbretia", "priority": "Critical"},
  "Crocus chrysanthus": {"common_name": "Golden crocus", "priority": "Low risk"},
  "Crocus speciosus": {"common_name": "Bieberstein's crocus", "priority": "Low risk"},
  "Crocus tommasinianus": {"common_name": "Early crocus", "priority": "Low risk"},
  "Crocus vernus": {"common_name": "Spring crocus", "priority": "Low risk"},
  "Cryptocoryne affinis": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne albida": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne aponogetifolia": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne balansae": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne beckettii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne bullosa": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne ciliata": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne cordata": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne cordata var.cordata 'Blassii'": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne crispatula var.tonkinensis": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne crispulata var.balansae": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne griffithii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne griffithii x C.cordata var.cordata": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne hudoroi": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne lingua": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne longicauda": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne minima": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne moehlmannii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne nurii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne parva": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne pontederiifolia": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne pygmaea": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne retrospiralis": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne scurillis": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne striolata": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne thwaitesii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne undulata": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne usteriana": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne walkerii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne wendtii": {"common_name": "", "priority": "Low risk"},
  "Cryptocoryne x willisii": {"common_name": "Dainty water-chalice", "priority": "Low risk"},
  "Cryptomeria japonica": {"common_name": "Japanese red-cedar", "priority": "Low risk"},
  "Cupressus macrocarpa": {"common_name": "Monterey cypress", "priority": "Low risk"},
  "Cyclamen coum": {"common_name": "Eastern sowbread", "priority": "Low risk"},
  "Cyclamen hederifolium": {"common_name": "Sowbread", "priority": "Low risk"},
  "Cymbalaria pallida": {"common_name": "Italian toadflax", "priority": "Moderate risk"},
  "Cyperus albostriatus 'Variegatus'": {"common_name": "", "priority": "Urgent"},
  "Cyperus alternifolius": {"common_name": "Umbrella plant", "priority": "Low risk"},
  "Cyperus eragrostis": {"common_name": "Pale galingale", "priority": "Critical"},
  "Cyperus haspan": {"common_name": "", "priority": "Moderate risk"},
  "Cyperus helferi": {"common_name": "", "priority": "Low risk"},
  "Cyperus involucratus": {"common_name": "Umbrella plant", "priority": "Low risk"},
  "Cyperus papyrus": {"common_name": "Papyrus", "priority": "Low risk"},
  "Cyperus prolifer": {"common_name": "Dwarf papyrus", "priority": "Low risk"},
  "Cyperus rotundus": {"common_name": "Purple nut sedge", "priority": "Urgent"},
  "Cytisus striatus": {"common_name": "Hairy-fruited broom", "priority": "Moderate risk"},
  "Darmera peltata": {"common_name": "Indian-rhubarb", "priority": "Low risk"},
  "Deutzia scabra": {"common_name": "Deutzia", "priority": "Low risk"},
  "Didiplis diandra": {"common_name": "Water hedge", "priority": "Low risk"},
  "Disphyma crassifolium": {"common_name": "Purple dewplant", "priority": "Critical"},
  "Dulichium arundinaceum": {"common_name": "Common three-way sedge", "priority": "Low risk"},
  "Echinochloa crus-galli": {"common_name": "Cockspur", "priority": "Low risk"},
  "Echinodorus amazonicus": {"common_name": "Amazon sword", "priority": "Low risk"},
  "Echinodorus andreuxii": {"common_name": "", "priority": "Low risk"},
  "Echinodorus argentinensis": {"common_name": "", "priority": "Moderate risk"},
  "Echinodorus berteroi": {"common_name": "Upright burhead", "priority": "Moderate risk"},
  "Echinodorus bleheri": {"common_name": "Amazon sword", "priority": "Low risk"},
  "Echinodorus bolivianus": {"common_name": "Bolivian sword plant", "priority": "Low risk"},
  "Echinodorus chrileni": {"common_name": "", "priority": "Low risk"},
  "Echinodorus compacta": {"common_name": "", "priority": "Low risk"},
  "Echinodorus cordifolius": {"common_name": "Creeping burhead", "priority": "Moderate risk"},
  "Echinodorus grisebachii": {"common_name": "", "priority": "Low risk"},
  "Echinodorus harbich": {"common_name": "", "priority": "Low risk"},
  "Echinodorus harbii": {"common_name": "", "priority": "Low risk"},
  "Echinodorus horemanii": {"common_name": "", "priority": "Low risk"},
  "Echinodorus horizontalis": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ‘Imperial’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ‘Ipica’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ‘Kleiner Bar’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus latifolius": {"common_name": "", "priority": "Low risk"},
  "Echinodorus magdalensis": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ‘Marble Queen’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus martii (E. major)": {"common_name": "", "priority": "Low risk"},
  "Echinodorus midi fleur": {"common_name": "", "priority": "Low risk"},
  "Echinodorus mitchii": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ‘Oriental’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus ozelot": {"common_name": "", "priority": "Low risk"},
  "Echinodorus paniculatus": {"common_name": "", "priority": "Low risk"},
  "Echinodorus parviflorus": {"common_name": "", "priority": "Moderate risk"},
  "Echinodorus quadricostata": {"common_name": "Chain sword", "priority": "Low risk"},
  "Echinodorus 'Red Flame'": {"common_name": "", "priority": "Low risk"},
  "Echinodorus 'Red Rubin'": {"common_name": "", "priority": "Low risk"},
  "Echinodorus 'Red Vein'": {"common_name": "", "priority": "Low risk"},
  "Echinodorus 'Rose'": {"common_name": "Indian red sword", "priority": "Low risk"},
  "Echinodorus scaber": {"common_name": "", "priority": "Low risk"},
  "Echinodorus schlueteri": {"common_name": "", "priority": "Low risk"},
  "Echinodorus schlueteri ‘Leopard’": {"common_name": "", "priority": "Low risk"},
  "Echinodorus tenellus": {"common_name": "Pygmy chain sword", "priority": "Moderate risk"},
  "Echinodorus tricolor": {"common_name": "", "priority": "Low risk"},
  "Echinodorus uruguayensis": {"common_name": "", "priority": "Moderate risk"},
  "Echinodorus uruguayensis x E. portoalegrensis": {"common_name": "", "priority": "Low risk"},
  "Echinodorus x barthii": {"common_name": "", "priority": "Low risk"},
  "Echinops exaltatus": {"common_name": "Globe-thistle", "priority": "Low risk"},
  "Echium pininana": {"common_name": "Giant viper's-bugloss", "priority": "Urgent"},
  "Egeria densa": {"common_name": "Large-flowered waterweed", "priority": "Critical"},
  "Eichhornia azurea": {"common_name": "", "priority": "Low risk"},
  "Eichhornia crassipes": {"common_name": "Water hyacinth", "priority": "Moderate risk"},
  "Eichhornia diversifolia": {"common_name": "", "priority": "Low risk"},
  "Eleocharis dulcis variegated": {"common_name": "Chinese water-chestnut", "priority": "Moderate risk"},
  "Eleocharis vivipara": {"common_name": "Umbrella hairgrass", "priority": "Low risk"},
  "Elodea callitrichoides": {"common_name": "South American waterweed", "priority": "Critical"},
  "Elodea canadensis": {"common_name": "Canadian waterweed", "priority": "Critical"},
  "Elodea nuttallii": {"common_name": "Nuttall's waterweed", "priority": "Critical"},
  "Equisetum camtschatcense": {"common_name": "Himalayan horsetail", "priority": "Low risk"},
  "Equisetum hyemale robustum": {"common_name": "", "priority": "Low risk"},
  "Equisetum hyemale var. affine": {"common_name": "", "priority": "Moderate risk"},
  "Equisetum japonicum": {"common_name": "", "priority": "Moderate risk"},
  "Equisetum ramosissimum var. japonicum": {"common_name": "Branched horsetail", "priority": "Moderate risk"},
  "Equisetum scirpoides": {"common_name": "Dwarf horsetail", "priority": "Critical"},
  "Erigeron glaucus": {"common_name": "Seaside daisy", "priority": "Moderate risk"},
  "Erigeron karvinskianus": {"common_name": "Mexican fleabane", "priority": "Urgent"},
  "Eriocaulon cinereum": {"common_name": "Ashy pipewort", "priority": "Moderate risk"},
  "Eriocaulon 'Guangzhou'": {"common_name": "", "priority": "Low risk"},
  "Eriocaulon setaceum": {"common_name": "Pipewort", "priority": "Low risk"},
  "Euphorbia amygdaloides subsp.robbiae": {"common_name": "", "priority": "Critical"},
  "Euphorbia characias": {"common_name": "Mediterranean spurge", "priority": "Low risk"},
  "Eusteralis stellata": {"common_name": "", "priority": "Moderate risk"},
  "Fallopia baldschuanica": {"common_name": "Russian-vine", "priority": "Critical"},
  "Fallopia japonica x sachalinensis": {"common_name": "Hybrid Japanese knotweed", "priority": "Critical"},
  "Fatsia japonica": {"common_name": "Fatsia", "priority": "Low risk"},
  "Forsythia suspensa x viridissima": {"common_name": "Forsythia", "priority": "Low risk"},
  "Galanthus caucasicus": {"common_name": "Caucasian snowdrop", "priority": "Low risk"},
  "Galanthus elwesii": {"common_name": "Greater snowdrop", "priority": "Low risk"},
  "Galanthus ikariae": {"common_name": "Green snowdrop", "priority": "Low risk"},
  "Galanthus plicatus": {"common_name": "Pleated snowdrop", "priority": "Low risk"},
  "Gaultheria mucronata": {"common_name": "Prickly heath", "priority": "Urgent"},
  "Genista hispanica": {"common_name": "Spanish gorse", "priority": "Low risk"},
  "Geranium endressii x versicolor": {"common_name": "French crane's-bill", "priority": "Urgent"},
  "Geranium ibericum x platypetalum": {"common_name": "Caucasian crane's-bill", "priority": "Low risk"},
  "Geranium macrorrhizum": {"common_name": "Rock crane's-bill", "priority": "Low risk"},
  "Glossostigma diandrum": {"common_name": "", "priority": "Critical"},
  "Glossostigma elatinoides": {"common_name": "", "priority": "Moderate risk"},
  "Gratiola officinalis": {"common_name": "Hedge hyssop", "priority": "Moderate risk"},
  "Griselinia littoralis": {"common_name": "New Zealand broadleaf", "priority": "Low risk"},
  "Gunnera tinctoria": {"common_name": "Giant-rhubarb", "priority": "Urgent"},
  "Gymnocoronis spilanthoides": {"common_name": "Senegal tea plant", "priority": "Moderate risk"},
  "Hebe brachysiphon": {"common_name": "Hooker's hebe", "priority": "Low risk"},
  "Hebe dieffenbachii": {"common_name": "Dieffenbach's hebe", "priority": "Low risk"},
  "Hedera colchica": {"common_name": "Persian ivy", "priority": "Critical"},
  "Helianthus annuus": {"common_name": "Sunflower", "priority": "Low risk"},
  "Helleborus argutifolius": {"common_name": "Corsican hellebore", "priority": "Low risk"},
  "Helleborus orientalis": {"common_name": "Lenten-rose", "priority": "Low risk"},
  "Hemianthus callitrichoides": {"common_name": "Pearl grass", "priority": "Low risk"},
  "Hemianthus micranthemoides": {"common_name": "Nuttalls' mudflower", "priority": "Low risk"},
  "Hemigraphis colorata": {"common_name": "Purple waffle", "priority": "Low risk"},
  "Hemigraphis exotica": {"common_name": "", "priority": "Low risk"},
  "Heteranthera bettzinckiana": {"common_name": "", "priority": "Low risk"},
  "Heteranthera dubia": {"common_name": "Buffalo grass", "priority": "Low risk"},
  "Heteranthera zosterifolia": {"common_name": "Stargrass", "priority": "Low risk"},
  "Heuchera sanguinea": {"common_name": "Coralbells", "priority": "Low risk"},
  "Holodiscus discolor": {"common_name": "Oceanspray", "priority": "Low risk"},
  "Hottonia inflata": {"common_name": "Featherfoil", "priority": "Low risk"},
  "Houttuynia cordata": {"common_name": "Lizard tail", "priority": "Critical"},
  "Hyacinthoides hispanica x non-scripta": {"common_name": "Spanish bluebell", "priority": "Critical"},
  "Hyacinthus orientalis": {"common_name": "Hyacinth", "priority": "Low risk"},
  "Hydrangea macrophylla": {"common_name": "Hydrangea", "priority": "Low risk"},
  "Hydrocleys nymphoides": {"common_name": "Water poppy", "priority": "Low risk"},
  "Hydrocotyle leucocephala": {"common_name": "Brazilian pennywort", "priority": "Low risk"},
  "Hydrocotyle novae-zelandiae": {"common_name": "New Zealand pennywort", "priority": "Low risk"},
  "Hydrocotyle ranunculoides": {"common_name": "Floating pennywort", "priority": "Critical"},
  "Hydrocotyle sibthorpioides": {"common_name": "Lawn marsh-pennywort", "priority": "Critical"},
  "Hydrocotyle variegata": {"common_name": "", "priority": "Low risk"},
  "Hydrocotyle verticillata": {"common_name": "Whorled marsh-pennywort", "priority": "Moderate risk"},
  "Hydrotriche hottoniiflora": {"common_name": "", "priority": "Low risk"},
  "Hygrophila angustifolia": {"common_name": "Willow hygro", "priority": "Low risk"},
  "Hygrophila corymbosa": {"common_name": "Starhorn", "priority": "Low risk"},
  "Hygrophila costata": {"common_name": "", "priority": "Low risk"},
  "Hygrophila difformis": {"common_name": "Water wisteria", "priority": "Low risk"},
  "Hygrophila lacustris": {"common_name": "Gulf swampweed", "priority": "Moderate risk"},
  "Hygrophila polysperma": {"common_name": "", "priority": "Low risk"},
  "Hygrophila rosae australis": {"common_name": "", "priority": "Low risk"},
  "Hygrophila rosanervis": {"common_name": "", "priority": "Low risk"},
  "Hygrophila salicifolia": {"common_name": "", "priority": "Low risk"},
  "Hygrophila thailand stricta": {"common_name": "", "priority": "Low risk"},
  "Hygroryza aristata": {"common_name": "", "priority": "Moderate risk"},
  "Hypericum forrestii": {"common_name": "Forrest's tutsan", "priority": "Low risk"},
  "Iberis sempervirens": {"common_name": "Perennial candytuft", "priority": "Low risk"},
  "Ilex aquifolium x perado": {"common_name": "Highclere holly", "priority": "Low risk"},
  "Iris ensata": {"common_name": "Japanese iris", "priority": "Low risk"},
  "Iris laevigata": {"common_name": "Japanese water iris", "priority": "Moderate risk"},
  "Iris orientalis": {"common_name": "Turkish iris", "priority": "Urgent"},
  "Isoetes japonica": {"common_name": "", "priority": "Low risk"},
  "Isoetes velata": {"common_name": "", "priority": "Low risk"},
  "Juncus 'Curly Gold Strike'": {"common_name": "", "priority": "Low risk"},
  "Juncus decipiens 'Curly-wurly'": {"common_name": "", "priority": "Low risk"},
  "Juncus ensifolius": {"common_name": "Swordleaf rush", "priority": "Critical"},
  "Juncus 'Goldstrike'": {"common_name": "", "priority": "Low risk"},
  "Juncus repens": {"common_name": "Lesser creeping rush", "priority": "Low risk"},
  "Juncus xiphioides": {"common_name": "Iris-leaved rush", "priority": "Urgent"},
  "Kerria japonica": {"common_name": "Kerria", "priority": "Moderate risk"},
  "Kniphofia uvaria": {"common_name": "Red-hot-poker", "priority": "Urgent"},
  "Kniphofia x praecox": {"common_name": "Greater red-hot-poker", "priority": "Urgent"},
  "Lagarosiphon major": {"common_name": "Curly waterweed", "priority": "Critical"},
  "Lagarosiphon muscoides": {"common_name": "", "priority": "Critical"},
  "Lagenandra ovata": {"common_name": "Malayan sword", "priority": "Low risk"},
  "Lagenandra thwaitesii": {"common_name": "", "priority": "Low risk"},
  "Lamiastrum galeobdolon subsp.argentatum": {"common_name": "Variegated yellow archangel", "priority": "Critical"},
  "Laurus nobilis": {"common_name": "Bay", "priority": "Critical"},
  "Lavandula angustifolia x latifolia": {"common_name": "Garden lavender", "priority": "Low risk"},
  "Lemna minuta": {"common_name": "Least duckweed", "priority": "Urgent"},
  "Ligustrum ovalifolium": {"common_name": "Garden privet", "priority": "Critical"},
  "Lilaeopsis brasiliensis": {"common_name": "Brazilian microsword", "priority": "Low risk"},
  "Lilaeopsis mauritiana": {"common_name": "", "priority": "Low risk"},
  "Lilaeopsis novae-zelandiae": {"common_name": "", "priority": "Low risk"},
  "Limnobium laevigatum": {"common_name": "Amazon frogbit", "priority": "Low risk"},
  "Limnobium spongia": {"common_name": "American spongeplant", "priority": "Critical"},
  "Limnophila aquatica": {"common_name": "Red temple", "priority": "Low risk"},
  "Limnophila aromatica": {"common_name": "Giant ambulia", "priority": "Low risk"},
  "Limnophila conferta": {"common_name": "", "priority": "Low risk"},
  "Limnophila gigantea": {"common_name": "", "priority": "Low risk"},
  "Limnophila heterophylla": {"common_name": "", "priority": "Low risk"},
  "Limnophila hippuroides": {"common_name": "", "priority": "Low risk"},
  "Limnophila sessiliflora": {"common_name": "Asian ambulia", "priority": "Low risk"},
  "Lindernia grandiflora": {"common_name": "Blue moneywort", "priority": "Moderate risk"},
  "Lindernia rotundiflora": {"common_name": "", "priority": "Low risk"},
  "Lobelia erinus": {"common_name": "Garden lobelia", "priority": "Low risk"},
  "Lonicera caprifolium x etrusca": {"common_name": "Perfoliate honeysuckle", "priority": "Low risk"},
  "Lonicera involucrata": {"common_name": "Californian honeysuckle", "priority": "Low risk"},
  "Lonicera japonica": {"common_name": "Japanese honeysuckle", "priority": "Critical"},
  "Lonicera nitida": {"common_name": "Wilson's honeysuckle", "priority": "Critical"},
  "Lonicera pileata": {"common_name": "Box-leaved honeysuckle", "priority": "Urgent"},
  "Ludwigia arcuata": {"common_name": "", "priority": "Low risk"},
  "Ludwigia brevipes": {"common_name": "Long beach primrose", "priority": "Low risk"},
  "Ludwigia glandulosa": {"common_name": "", "priority": "Low risk"},
  "Ludwigia grandiflora": {"common_name": "Water primrose", "priority": "Critical"},
  "Ludwigia helminthorrhiza": {"common_name": "", "priority": "Low risk"},
  "Ludwigia inclinata": {"common_name": "", "priority": "Low risk"},
  "Ludwigia inclinata verticillate 'Pantanale'": {"common_name": "", "priority": "Low risk"},
  "Ludwigia latifolia": {"common_name": "", "priority": "Low risk"},
  "Ludwigia ovalis": {"common_name": "", "priority": "Moderate risk"},
  "Ludwigia peploides": {"common_name": "Floating primrose willow", "priority": "Critical"},
  "Ludwigia perennis": {"common_name": "", "priority": "Low risk"},
  "Ludwigia repens": {"common_name": "Creeping primrose willow", "priority": "Critical"},
  "Ludwigia x kentiana": {"common_name": "Hampshire-purslane", "priority": "Moderate risk"},
  "Lupinus arboreus": {"common_name": "Tree lupin", "priority": "Urgent"},
  "Lupinus arboreus x polyphyllus": {"common_name": "Tree lupin (L. x regalis)", "priority": "Urgent"},
  "Lysichiton americanus": {"common_name": "American skunk-cabbage", "priority": "Moderate risk"},
  "Lysichiton camtschatcensis": {"common_name": "Asian skunk-cabbage", "priority": "Low risk"},
  "Lythrum virgatum 'Dropmore Purple'": {"common_name": "Purple loosestrife 'Dropmore Purple'", "priority": "Moderate risk"},
  "Marsilea crenata": {"common_name": "", "priority": "Low risk"},
  "Marsilea quadrifolia": {"common_name": "European water clover", "priority": "Low risk"},
  "Marsilea hirsuta": {"common_name": "Rough water clover", "priority": "Moderate risk"},
  "Mayaca fluviatilis": {"common_name": "Green mayaca", "priority": "Moderate risk"},
  "Mayaca sellowiana": {"common_name": "", "priority": "Low risk"},
  "Mayaca vandelli": {"common_name": "", "priority": "Low risk"},
  "Mentha cervina": {"common_name": "Hart's pennyroyal", "priority": "Low risk"},
  "Micranthemum umbrosum": {"common_name": "Shade mudflower", "priority": "Critical"},
  "Microsorum latifolius": {"common_name": "", "priority": "Low risk"},
  "Microsorum pteropus": {"common_name": "Java fern", "priority": "Low risk"},
  "Mimulus cupreus x guttatus": {"common_name": "Scarlet monkeyflower", "priority": "Low risk"},
  "Monochoria hastata": {"common_name": "", "priority": "Low risk"},
  "Monosolenium tenerum": {"common_name": "", "priority": "Low risk"},
  "Morus nigra": {"common_name": "Black mulberry", "priority": "Low risk"},
  "Myriophyllum aquaticum": {"common_name": "Parrot's-feather", "priority": "Critical"},
  "Myriophyllum elatinoides": {"common_name": "New Zealand water-milfoil", "priority": "Critical"},
  "Myriophyllum hippuroides": {"common_name": "Western milfoil", "priority": "Urgent"},
  "Myriophyllum matogrossense": {"common_name": "", "priority": "Low risk"},
  "Myriophyllum pinnatum": {"common_name": "", "priority": "Urgent"},
  "Myriophyllum propinquum": {"common_name": "", "priority": "Urgent"},
  "Myriophyllum propium": {"common_name": "", "priority": "Urgent"},
  "Myriophyllum 'Red Stem'": {"common_name": "", "priority": "Urgent"},
  "Myriophyllum tuberculatum": {"common_name": "", "priority": "Low risk"},
  "Nelumbo nucifera": {"common_name": "Indian lotus", "priority": "Low risk"},
  "Neobeckia aquatica": {"common_name": "Lake cress", "priority": "Low risk"},
  "Nesaea crassicaulis": {"common_name": "", "priority": "Low risk"},
  "Nicandra physalodes": {"common_name": "Apple-of-Peru", "priority": "Low risk"},
  "Nicotiana alata x forgetiana": {"common_name": "Sweet tobacco", "priority": "Low risk"},
  "Nicotiana forgetiana": {"common_name": "Red tobacco", "priority": "Low risk"},
  "Nigella damascena": {"common_name": "Love-in-a-mist", "priority": "Low risk"},
  "Nomaphila siamensis": {"common_name": "", "priority": "Low risk"},
  "Nomaphila stricta": {"common_name": "", "priority": "Low risk"},
  "Nomaphila variegata": {"common_name": "", "priority": "Low risk"},
  "Nothofagus nervosa": {"common_name": "Dombey's beech", "priority": "Low risk"},
  "Nothofagus obliqua": {"common_name": "Roble", "priority": "Low risk"},
  "Nuphar advena": {"common_name": "Beaver lily", "priority": "Low risk"},
  "Nuphar japonicum": {"common_name": "", "priority": "Moderate risk"},
  "Nymphaea mexicana": {"common_name": "Banana water lily", "priority": "Low risk"},
  "Nymphaea odorata": {"common_name": "Fragrant water lily", "priority": "Moderate risk"},
  "Nymphaea odorata subsp. tuberosa": {"common_name": "", "priority": "Moderate risk"},
  "Nymphaea odorata var. minor": {"common_name": "Lesser fragrant water lily", "priority": "Low risk"},
  "Nymphaea pubescens": {"common_name": "Purple water Lily", "priority": "Moderate risk"},
  "Nymphaea tetragona": {"common_name": "Pigmy water lily", "priority": "Urgent"},
  "Nymphaea zenkeri": {"common_name": "Red tiger lotus", "priority": "Low risk"},
  "Nymphoides aquatica": {"common_name": "Banana plant", "priority": "Moderate risk"},
  "Oenanthe javanica 'Flamingo'": {"common_name": "", "priority": "Critical"},
  "Olearia macrodonta": {"common_name": "New Zealand holly", "priority": "Low risk"},
  "Orontium aquaticum": {"common_name": "Golden club", "priority": "Critical"},
  "Ottelia ulvifolia": {"common_name": "", "priority": "Low risk"},
  "Oxalis exilis": {"common_name": "Least yellow-sorrel", "priority": "Low risk"},
  "Oxalis latifolia": {"common_name": "Garden pink-sorrel", "priority": "Urgent"},
  "Paeonia officinalis": {"common_name": "Garden peony", "priority": "Low risk"},
  "Papaver atlanticum": {"common_name": "Atlas poppy", "priority": "Low risk"},
  "Parthenocissus inserta": {"common_name": "False Virginia-creeper", "priority": "Moderate risk"},
  "Parthenocissus quinquefolia": {"common_name": "Virginia-creeper", "priority": "Urgent"},
  "Paulownia tomentosa": {"common_name": "Foxglove-tree", "priority": "Low risk"},
  "Peltandra sagittifolia": {"common_name": "Spoonflower", "priority": "Low risk"},
  "Peltandra virginica": {"common_name": "Green arrow arum", "priority": "Critical"},
  "Persicaria campanulata": {"common_name": "Lesser knotweed", "priority": "Critical"},
  "Persicaria wallichii": {"common_name": "Himalayan knotweed", "priority": "Critical"},
  "Petasites japonicus": {"common_name": "Giant butterbur", "priority": "Critical"},
  "Petunia axillaris x integrifolia": {"common_name": "Petunia", "priority": "Low risk"},
  "Phacelia tanacetifolia": {"common_name": "Phacelia", "priority": "Low risk"},
  "Phalaris paradoxa": {"common_name": "Awned canary-grass", "priority": "Low risk"},
  "Philadelphus coronarius": {"common_name": "Mock-orange", "priority": "Low risk"},
  "Philadelphus x virginalis": {"common_name": "Hairy mock-orange", "priority": "Low risk"},
  "Photinia davidiana": {"common_name": "Stranvaesia", "priority": "Low risk"},
  "Phyllanthus fluitans": {"common_name": "Red root floater", "priority": "Low risk"},
  "Physalis peruviana": {"common_name": "Cape-gooseberry", "priority": "Low risk"},
  "Picea sitchensis": {"common_name": "Sitka spruce", "priority": "Critical"},
  "Pinus contorta": {"common_name": "Lodgepole pine", "priority": "Urgent"},
  "Pinus nigra": {"common_name": "Austrian pine, Corsican pine", "priority": "Critical"},
  "Pinus strobus": {"common_name": "Weymouth pine", "priority": "Low risk"},
  "Pistia stratiotes": {"common_name": "Water lettuce", "priority": "Moderate risk"},
  "Pittosporum tenuifolium": {"common_name": "Kohuhu", "priority": "Low risk"},
  "Platanus x hispanica": {"common_name": "Oriental plane", "priority": "Low risk"},
  "Pogostemon helferi": {"common_name": "", "priority": "Low risk"},
  "Polypogon viridis": {"common_name": "Water bent", "priority": "Low risk"},
  "Pontederia cordata": {"common_name": "Pickerelweed", "priority": "Urgent"},
  "Pontederia lanceolata": {"common_name": "", "priority": "Low risk"},
  "Populus trichocarpa": {"common_name": "Western balsam-poplar", "priority": "Low risk"},
  "Proserpinaca palustris": {"common_name": "Mermaid weed", "priority": "Moderate risk"},
  "Prunus lusitanica": {"common_name": "Portugal laurel", "priority": "Critical"},
  "Prunus serrulata": {"common_name": "Japanese cherry", "priority": "Low risk"},
  "Pseudofumaria alba": {"common_name": "Pale corydalis", "priority": "Low risk"},
  "Pseudosasa japonica": {"common_name": "Arrow bamboo", "priority": "Critical"},
  "Pterocarya fraxinifolia": {"common_name": "Caucasian wingnut", "priority": "Low risk"},
  "Pyracantha coccinea": {"common_name": "Firethorn", "priority": "Critical"},
  "Pyracantha rogersiana": {"common_name": "Asian firethorn", "priority": "Critical"},
  "Quercus cerris": {"common_name": "Turkey oak", "priority": "Critical"},
  "Quercus cerris x suber": {"common_name": "Turkey oak (Q. x crenata)", "priority": "Low risk"},
  "Quercus ilex": {"common_name": "Evergreen oak", "priority": "Critical"},
  "Quercus rubra": {"common_name": "Red oak", "priority": "Critical"},
  "Ranunculus limosella": {"common_name": "Mud buttercup", "priority": "Low risk"},
  "Rheum x hybridum": {"common_name": "Rhubarb", "priority": "Low risk"},
  "Rhododendron luteum": {"common_name": "Yellow azalea", "priority": "Moderate risk"},
  "Rhododendron ponticum x R. maximum": {"common_name": "Rhododendron hybrid", "priority": "Critical"},
  "Rhus typhina": {"common_name": "Stag's-horn sumach", "priority": "Moderate risk"},
  "Rhynchospora colorata": {"common_name": "Star sedge", "priority": "Low risk"},
  "Ribes odoratum": {"common_name": "Buffalo currant", "priority": "Critical"},
  "Robinia pseudoacacia": {"common_name": "False-acacia", "priority": "Critical"},
  "Rosa ferruginea": {"common_name": "Red-leaved rose", "priority": "Urgent"},
  "Rosa 'Hollandica'": {"common_name": "Dutch rose", "priority": "Moderate risk"},
  "Rosa multiflora": {"common_name": "Many-flowered rose", "priority": "Critical"},
  "Rosa rugosa": {"common_name": "Japanese rose", "priority": "Critical"},
  "Rosmarinus officinalis": {"common_name": "Rosemary", "priority": "Low risk"},
  "Rotala indica": {"common_name": "", "priority": "Low risk"},
  "Rotala macrandra": {"common_name": "", "priority": "Low risk"},
  "Rotala rotundifolia": {"common_name": "", "priority": "Critical"},
  "Rotala wallichii": {"common_name": "", "priority": "Low risk"},
  "Rubus cockburnianus": {"common_name": "White-stemmed bramble", "priority": "Critical"},
  "Rubus tricolor": {"common_name": "Chinese bramble", "priority": "Critical"},
  "Rumex cristatus": {"common_name": "Greek dock", "priority": "Low risk"},
  "Sagittaria 'Bloomin Babe'": {"common_name": "", "priority": "Low risk"},
  "Sagittaria filiformis": {"common_name": "Threadleaf arrowhead", "priority": "Low risk"},
  "Sagittaria graminea": {"common_name": "Grassy arrowhead", "priority": "Urgent"},
  "Sagittaria latifolia": {"common_name": "Duck-potato", "priority": "Critical"},
  "Sagittaria lileopterus": {"common_name": "", "priority": "Low risk"},
  "Sagittaria platyphylla": {"common_name": "", "priority": "Moderate risk"},
  "Sagittaria sagittifolia subsp. leucopetala": {"common_name": "", "priority": "Critical"},
  "Sagittaria subulata": {"common_name": "Narrow-leaved arrowhead", "priority": "Urgent"},
  "Sagittaria teres": {"common_name": "Slender arrowhead", "priority": "Urgent"},
  "Salix x calodendron": {"common_name": "Holme willow", "priority": "Low risk"},
  "Salvinia auriculata": {"common_name": "", "priority": "Low risk"},
  "Salvinia cucullata": {"common_name": "", "priority": "Low risk"},
  "Salvinia molesta": {"common_name": "Giant salvinia", "priority": "Low risk"},
  "Salvinia natans": {"common_name": "", "priority": "Urgent"},
  "Salvinia oblongifolia": {"common_name": "", "priority": "Low risk"},
  "Samolus valerandi subsp. parviflorus": {"common_name": "Water pimpernel", "priority": "Moderate risk"},
  "Sasa palmata": {"common_name": "Broad-leaved bamboo", "priority": "Critical"},
  "Sasaella ramosa": {"common_name": "Hairy bamboo", "priority": "Critical"},
  "Saururus cernuus": {"common_name": "Lizards tail", "priority": "Critical"},
  "Saururus chinensis": {"common_name": "Lizards tail", "priority": "Moderate risk"},
  "Schoenus pauciflorus": {"common_name": "", "priority": "Moderate risk"},
  "Scilla bifolia": {"common_name": "Alpine squill", "priority": "Low risk"},
  "Scilla siberica": {"common_name": "Siberian squill", "priority": "Low risk"},
  "Sedum kamtschaticum": {"common_name": "Kamchatka stonecrop", "priority": "Low risk"},
  "Sedum spectabile": {"common_name": "Butterfly stonecrop", "priority": "Low risk"},
  "Selaginella wildenowii": {"common_name": "", "priority": "Low risk"},
  "Senecio inaequidens": {"common_name": "Narrow-leaved ragwort", "priority": "Low risk"},
  "Senecio squalidus x viscosus": {"common_name": "Oxford ragwort", "priority": "Low risk"},
  "Sequoiadendron giganteum": {"common_name": "Wellingtonia", "priority": "Low risk"},
  "Sisyrinchium striatum": {"common_name": "Pale yellow-eyed-grass", "priority": "Low risk"},
  "Solanum physalifolium": {"common_name": "Green nightshade", "priority": "Low risk"},
  "Sorbaria sorbifolia": {"common_name": "Sorbaria", "priority": "Critical"},
  "Sorbaria tomentosa": {"common_name": "Himalayan sorbaria", "priority": "Low risk"},
  "Sorbus hybrida": {"common_name": "Swedish service-tree", "priority": "Low risk"},
  "Sorghum halepense": {"common_name": "Johnson-grass", "priority": "Low risk"},
  "Spiraea alba x douglasii (S. x billardii)": {"common_name": "Pale bridewort", "priority": "Low risk"},
  "Spiraea alba x salicifolia": {"common_name": "Billard's bridewort", "priority": "Moderate risk"},
  "Spiraea cantoniensis x trilobata": {"common_name": "Himalayan spiraea", "priority": "Low risk"},
  "Spiraea douglasii x salicifolia": {"common_name": "Lange's spiraea", "priority": "Urgent"},
  "Stachys byzantina": {"common_name": "Lamb's-ear", "priority": "Low risk"},
  "Stenotaphrum secundatum variegatum": {"common_name": "St. Augustine grass", "priority": "Low risk"},
  "Symphoricarpos microphyllus x orbicularis": {"common_name": "Snowberry", "priority": "Urgent"},
  "Symphytum 'Hidcote Blue'": {"common_name": "Creeping comfrey", "priority": "Low risk"},
  "Syngonium podophyllum": {"common_name": "Nephthytis", "priority": "Low risk"},
  "Syngonium ‘Red Knight’": {"common_name": "", "priority": "Low risk"},
  "Thalia dealbata": {"common_name": "Powdery alligator-flag", "priority": "Moderate risk"},
  "Thalia geniculata": {"common_name": "Swamp lily", "priority": "Urgent"},
  "Thuja plicata": {"common_name": "Western red-cedar", "priority": "Urgent"},
  "Tonina fluviatilis": {"common_name": "", "priority": "Low risk"},
  "Trapa natans": {"common_name": "Water chestnut", "priority": "Urgent"},
  "Trichocoronis rivularis": {"common_name": "", "priority": "Moderate risk"},
  "Trichomanes javanicum": {"common_name": "", "priority": "Low risk"},
  "Tristagma uniflorum": {"common_name": "Spring starflower", "priority": "Low risk"},
  "Tulipa gesneriana": {"common_name": "Garden tulip", "priority": "Low risk"},
  "Typha gracilis": {"common_name": "Slender cattail", "priority": "Critical"},
  "Typha laxmannii": {"common_name": "", "priority": "Critical"},
  "Typha minima": {"common_name": "", "priority": "Critical"},
  "Typha shuttleworthii": {"common_name": "", "priority": "Moderate risk"},
  "Typhonodorum lindleyanum": {"common_name": "", "priority": "Low risk"},
  "Utricularia gibba": {"common_name": "Humped bladderwort", "priority": "Urgent"},
  "Utricularia sandersonii": {"common_name": "", "priority": "Moderate risk"},
  "Vallisneria americana": {"common_name": "", "priority": "Urgent"},
  "Vallisneria asiatica": {"common_name": "", "priority": "Urgent"},
  "Vallisneria natans var. natans": {"common_name": "", "priority": "Moderate risk"},
  "Vallisneria rubra": {"common_name": "", "priority": "Low risk"},
  "Vallisneria spiralis": {"common_name": "Tape grass", "priority": "Urgent"},
  "Vallisneria tortifolia": {"common_name": "", "priority": "Moderate risk"},
  "Verbascum densiflorum": {"common_name": "Dense-flowered mullein", "priority": "Low risk"},
  "Vesicularia dubyana": {"common_name": "", "priority": "Low risk"},
  "Vesicularia ferriei": {"common_name": "Weeping moss", "priority": "Low risk"},
  "Vesicularia montagnei": {"common_name": "Christmas moss", "priority": "Low risk"},
  "Viburnum rhytidophyllum": {"common_name": "Wrinkled viburnum", "priority": "Urgent"},
  "Viola x wittrockiana": {"common_name": "Garden pansy", "priority": "Low risk"},
  "Yucca recurvifolia": {"common_name": "Curved-leaved Spanish-dagger", "priority": "Low risk"},
  "Yushania anceps": {"common_name": "Indian fountain-bamboo", "priority": "Critical"},
  "Zantedeschia aethiopica": {"common_name": "Altar-lily", "priority": "Low risk"}
}